from __future__ import annotations

from typing import Iterable

REASON_CODE_COOLDOWN_ACTIVE = "cooldown_active"
REASON_CODE_EMA_MOMENTUM_LONG = "ema_momentum_long"
REASON_CODE_EMA_MOMENTUM_SHORT = "ema_momentum_short"
REASON_CODE_NO_TRADE_SETUP = "no_trade_setup"
REASON_CODE_BELOW_MIN_CONFIDENCE = "below_min_confidence"
REASON_CODE_FORCED_HOLD = "forced_hold"

REASON_CODE_EXECUTE_ORDERS_DISABLED = "execute_orders_disabled"
REASON_CODE_LIVE_HTTP_DISABLED = "live_http_disabled"
REASON_CODE_STREAM_RECONNECTING = "stream_reconnecting"
REASON_CODE_STREAM_DEGRADED = "stream_degraded"
REASON_CODE_ORDER_FETCH_FAILED = "order_fetch_failed"
REASON_CODE_ORDER_CANCEL_FAILED = "order_cancel_failed"
REASON_CODE_ORDER_REJECTED = "order_rejected"

REASON_CODE_MAX_DRAWDOWN_EXCEEDED = "max_drawdown_exceeded"
REASON_CODE_DAILY_LOSS_LIMIT_EXCEEDED = "daily_loss_limit_exceeded"
REASON_CODE_MAX_POSITION_SIZE_EXCEEDED = "max_position_size_exceeded"
REASON_CODE_MAX_TRADE_LOSS_EXCEEDED = "max_trade_loss_exceeded"
REASON_CODE_MAX_LEVERAGE_EXCEEDED = "max_leverage_exceeded"
REASON_CODE_WALLET_DRIFT_EXCEEDED = "wallet_drift_exceeded"

REASON_CODE_MISSING_CREDENTIALS = "missing_credentials"
REASON_CODE_MONITOR_DISABLED = "monitor_disabled"
REASON_CODE_RISK_LIMIT_EXCEEDED = "risk_limit_exceeded"
REASON_CODE_RATE_LIMIT = "rate_limit"
REASON_CODE_EXCHANGE_VALIDATION_ERROR = "exchange_validation_error"
REASON_CODE_NETWORK_TIMEOUT = "network_timeout"
REASON_CODE_GRACEFUL_SHUTDOWN_REQUESTED = "graceful_shutdown_requested"

REASON_CODES = {
    REASON_CODE_COOLDOWN_ACTIVE,
    REASON_CODE_EMA_MOMENTUM_LONG,
    REASON_CODE_EMA_MOMENTUM_SHORT,
    REASON_CODE_NO_TRADE_SETUP,
    REASON_CODE_BELOW_MIN_CONFIDENCE,
    REASON_CODE_FORCED_HOLD,
    REASON_CODE_EXECUTE_ORDERS_DISABLED,
    REASON_CODE_LIVE_HTTP_DISABLED,
    REASON_CODE_STREAM_RECONNECTING,
    REASON_CODE_STREAM_DEGRADED,
    REASON_CODE_ORDER_FETCH_FAILED,
    REASON_CODE_ORDER_CANCEL_FAILED,
    REASON_CODE_ORDER_REJECTED,
    REASON_CODE_MAX_DRAWDOWN_EXCEEDED,
    REASON_CODE_DAILY_LOSS_LIMIT_EXCEEDED,
    REASON_CODE_MAX_POSITION_SIZE_EXCEEDED,
    REASON_CODE_MAX_TRADE_LOSS_EXCEEDED,
    REASON_CODE_MAX_LEVERAGE_EXCEEDED,
    REASON_CODE_WALLET_DRIFT_EXCEEDED,
    REASON_CODE_MISSING_CREDENTIALS,
    REASON_CODE_MONITOR_DISABLED,
    REASON_CODE_RISK_LIMIT_EXCEEDED,
    REASON_CODE_RATE_LIMIT,
    REASON_CODE_EXCHANGE_VALIDATION_ERROR,
    REASON_CODE_NETWORK_TIMEOUT,
    REASON_CODE_GRACEFUL_SHUTDOWN_REQUESTED,
}


def normalize_reason_codes(codes: Iterable[str]) -> list[str]:
    return [code for code in codes if code in REASON_CODES]
